import json
from typing import AsyncGenerator, Dict, Any, Optional, List
import httpx
from app.services.llm.base import BaseLLMProvider
from app.core.config import settings
from app.core.gemini_models import DEFAULT_GEMINI_MODEL, normalize_gemini_model
from app.core.logging_service import app_logger

GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"


def _word_packets(text: str):
    buf = ""
    for ch in text:
        buf += ch
        if ch.isspace() and len(buf) >= 2:
            yield buf
            buf = ""
    if buf:
        yield buf


class GeminiLLMProvider(BaseLLMProvider):
    """Integrates directly with Google Gemini REST API using the user's free API key."""

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.api_key = api_key or settings.llm_api_key or settings.gemini_api_key or ""
        self.model = normalize_gemini_model(
            model or settings.llm_model_name or settings.gemini_model_name or DEFAULT_GEMINI_MODEL
        )

    def _get_url(self, action: str = "generateContent") -> str:
        return f"{GEMINI_API_BASE}/{self.model}:{action}?key={self.api_key}"

    async def generate(
        self,
        prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.4,
        stop: Optional[List[str]] = None
    ) -> str:
        if not self.api_key:
            raise RuntimeError("Gemini API Key is missing. Please enter your free Gemini API key in Settings.")

        url = self._get_url("generateContent")
        payload = {
            "contents": [
                {
                    "parts": [{"text": prompt}]
                }
            ],
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens
            }
        }
        if stop:
            payload["generationConfig"]["stopSequences"] = stop

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                response = await client.post(url, json=payload, headers={"Content-Type": "application/json"})
                if response.status_code != 200:
                    err_text = response.text
                    try:
                        err_json = response.json()
                        err_text = err_json.get("error", {}).get("message", err_text)
                    except Exception:
                        pass
                    app_logger.error("GeminiLLM", f"Gemini API Error {response.status_code}: {err_text}")
                    raise RuntimeError(f"Gemini API Error: {err_text}")

                data = response.json()
                candidates = data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "").strip()
                return "(No text generated by Gemini)"
            except httpx.HTTPStatusError as e:
                raise RuntimeError(f"Gemini API HTTP Error: {e}")
            except Exception as e:
                app_logger.error("GeminiLLM", f"Error generating completion: {e}")
                raise

    async def stream_generate(
        self,
        prompt: str,
        max_tokens: int = 1024,
        temperature: float = 0.4,
        stop: Optional[List[str]] = None
    ) -> AsyncGenerator[str, None]:
        if not self.api_key:
            raise RuntimeError("Gemini API Key is missing. Please enter your free Gemini API key in Settings.")

        url = self._get_url("streamGenerateContent") + "&alt=sse"
        payload = {
            "contents": [
                {
                    "parts": [{"text": prompt}]
                }
            ],
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens
            }
        }
        if stop:
            payload["generationConfig"]["stopSequences"] = stop

        async with httpx.AsyncClient(timeout=90.0) as client:
            try:
                async with client.stream("POST", url, json=payload, headers={"Content-Type": "application/json"}) as response:
                    if response.status_code != 200:
                        full_text = await self.generate(prompt, max_tokens, temperature, stop)
                        for packet in _word_packets(full_text):
                            yield packet
                        return

                    seen = ""
                    async for line in response.aiter_lines():
                        if not line or not line.startswith("data:"):
                            continue
                        data_str = line[5:].strip()
                        if not data_str:
                            continue
                        try:
                            chunk = json.loads(data_str)
                            candidates = chunk.get("candidates", [])
                            if not candidates:
                                continue
                            parts = candidates[0].get("content", {}).get("parts", [])
                            piece = "".join(p.get("text", "") for p in parts if p.get("text"))
                            if not piece:
                                continue
                            if piece.startswith(seen):
                                delta = piece[len(seen):]
                                seen = piece
                            else:
                                delta = piece
                                seen += piece
                            if delta:
                                yield delta
                        except Exception:
                            continue
            except Exception as e:
                app_logger.warning("GeminiLLM", f"Stream error ({e}), falling back to paced non-streaming...")
                full_text = await self.generate(prompt, max_tokens, temperature, stop)
                for packet in _word_packets(full_text):
                    yield packet

    async def check_health(self) -> Dict[str, Any]:
        if not self.api_key:
            return {"status": "disconnected", "error": "Gemini API Key not set"}

        url = f"{GEMINI_API_BASE}?key={self.api_key}"
        async with httpx.AsyncClient(timeout=5.0) as client:
            try:
                res = await client.get(url)
                if res.status_code == 200:
                    return {"status": "connected", "provider": "gemini", "model": self.model}
                else:
                    err_msg = res.text
                    try:
                        err_msg = res.json().get("error", {}).get("message", err_msg)
                    except Exception:
                        pass
                    return {"status": "error", "error": err_msg}
            except Exception as e:
                return {"status": "disconnected", "error": str(e)}
